/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class f */

#ifndef _Included_f
#define _Included_f
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     f
 * Method:    function
 * Signature: ([F)F
 */
JNIEXPORT jfloat JNICALL Java_f_function
  (JNIEnv *, jclass, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
