/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Demo */

#ifndef _Included_Demo
#define _Included_Demo
#ifdef __cplusplus
extern "C" {
#endif
#undef Demo_FOCUS_TRAVERSABLE_UNKNOWN
#define Demo_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef Demo_FOCUS_TRAVERSABLE_DEFAULT
#define Demo_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef Demo_FOCUS_TRAVERSABLE_SET
#define Demo_FOCUS_TRAVERSABLE_SET 2L
#undef Demo_TOP_ALIGNMENT
#define Demo_TOP_ALIGNMENT 0.0f
#undef Demo_CENTER_ALIGNMENT
#define Demo_CENTER_ALIGNMENT 0.5f
#undef Demo_BOTTOM_ALIGNMENT
#define Demo_BOTTOM_ALIGNMENT 1.0f
#undef Demo_LEFT_ALIGNMENT
#define Demo_LEFT_ALIGNMENT 0.0f
#undef Demo_RIGHT_ALIGNMENT
#define Demo_RIGHT_ALIGNMENT 1.0f
#undef Demo_serialVersionUID
#define Demo_serialVersionUID -7644114512714619750LL
#undef Demo_serialVersionUID
#define Demo_serialVersionUID 4613797578919906343LL
#undef Demo_INCLUDE_SELF
#define Demo_INCLUDE_SELF 1L
#undef Demo_SEARCH_HEAVYWEIGHTS
#define Demo_SEARCH_HEAVYWEIGHTS 1L
#undef Demo_OPENED
#define Demo_OPENED 1L
#undef Demo_serialVersionUID
#define Demo_serialVersionUID 4497834738069338734LL
#undef Demo_DEFAULT_CURSOR
#define Demo_DEFAULT_CURSOR 0L
#undef Demo_CROSSHAIR_CURSOR
#define Demo_CROSSHAIR_CURSOR 1L
#undef Demo_TEXT_CURSOR
#define Demo_TEXT_CURSOR 2L
#undef Demo_WAIT_CURSOR
#define Demo_WAIT_CURSOR 3L
#undef Demo_SW_RESIZE_CURSOR
#define Demo_SW_RESIZE_CURSOR 4L
#undef Demo_SE_RESIZE_CURSOR
#define Demo_SE_RESIZE_CURSOR 5L
#undef Demo_NW_RESIZE_CURSOR
#define Demo_NW_RESIZE_CURSOR 6L
#undef Demo_NE_RESIZE_CURSOR
#define Demo_NE_RESIZE_CURSOR 7L
#undef Demo_N_RESIZE_CURSOR
#define Demo_N_RESIZE_CURSOR 8L
#undef Demo_S_RESIZE_CURSOR
#define Demo_S_RESIZE_CURSOR 9L
#undef Demo_W_RESIZE_CURSOR
#define Demo_W_RESIZE_CURSOR 10L
#undef Demo_E_RESIZE_CURSOR
#define Demo_E_RESIZE_CURSOR 11L
#undef Demo_HAND_CURSOR
#define Demo_HAND_CURSOR 12L
#undef Demo_MOVE_CURSOR
#define Demo_MOVE_CURSOR 13L
#undef Demo_NORMAL
#define Demo_NORMAL 0L
#undef Demo_ICONIFIED
#define Demo_ICONIFIED 1L
#undef Demo_MAXIMIZED_HORIZ
#define Demo_MAXIMIZED_HORIZ 2L
#undef Demo_MAXIMIZED_VERT
#define Demo_MAXIMIZED_VERT 4L
#undef Demo_MAXIMIZED_BOTH
#define Demo_MAXIMIZED_BOTH 6L
#undef Demo_serialVersionUID
#define Demo_serialVersionUID 2673458971256075116LL
#undef Demo_EXIT_ON_CLOSE
#define Demo_EXIT_ON_CLOSE 3L
/*
 * Class:     Demo
 * Method:    gtk_draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Demo_gtk_1draw
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
