/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Toa1_String2char */

#ifndef _Included_Toa1_String2char
#define _Included_Toa1_String2char
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Toa1_String2char
 * Method:    function
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Toa1_1String2char_function
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
