/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 06月 14日 星期五 09:05:33 CST. */
/* 
 Copyright (C) Rong Tao @Beijing

 Permission is granted to copy, distribute and/or modify this document
 under the terms of the GNU Free Documentation License, Version 1.3
 or any later version published by the Free Software Foundation;
 with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
 Texts. A copy of the license is included in the section entitled ‘‘GNU
 Free Documentation License’’.
   2019年 03月 14日 星期四 19:24:34 CST. 
*/
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 13日 星期三 08:54:06 CST. */
/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 08日 星期五 08:10:18 CST. */
/* Copyright (c) Colorado School of Mines, CST.*/
/* All rights reserved.                       */

/* Copyright (C) Rong Tao @Sylincom Beijing, 2019年 03月 07日 星期四 20:27:55 CST. */
/*
char * strptime (const char *s, const char *fmt, struct tm *tp) [Function]
The strptime function parses the input string s according to the format string fmt
and stores its results in the structure tp.
The input string could be generated by a strftime call or obtained any other
way. It does not need to be in a human-recognizable format; e.g. a date passed
as "02:1999:9" is acceptable, even though it is ambiguous without context. As long
as the format string fmt matches the input string the function will succeed.
The user has to make sure, though, that the input can be parsed in a unambiguous
way. The string "1999112" can be parsed using the format "%Y%m%d" as 1999-1-12,

1999-11-2, or even 19991-1-2. It is necessary to add appropriate separators to reliably
get results.
The format string consists of the same components as the format string of the
strftime function. The only diﬀerence is that the ﬂags _, -, 0, and ^ are not
allowed. Several of the distinct formats of strftime do the same work in strptime
since diﬀerences like case of the input do not matter. For reasons of symmetry all
formats are supported, though.
The modifers E and O are also allowed everywhere the strftime function allows them.
The formats are:
%a
%A The weekday name according to the current locale, in abbreviated form
or the full name.
%b
%B
%h The month name according to the current locale, in abbreviated form or
the full name.
%c The date and time representation for the current locale.
%Ec Like %c but the locale’s alternative date and time format is used.
%C The century of the year.
It makes sense to use this format only if the format string also contains
the %y format.
%EC The locale’s representation of the period.
Unlike %C it sometimes makes sense to use this format since some cul
tures represent years relative to the beginning of eras instead of using the
Gregorian years.
%d
%e The day of the month as a decimal number (range 1 through 31). Leading
zeroes are permitted but not required.
%Od
%Oe Same as %d but using the locale’s alternative numeric symbols.
Leading zeroes are permitted but not required.
%D Equivalent to %m/%d/%y.
%F Equivalent to %Y-%m-%d, which is the ISO 8601 date format.
This is a GNU extension following an ISO C99 extension to strftime.
%g The year corresponding to the ISO week number, but without the century
(range 00 through 99).
Note: Currently, this is not fully implemented. The format is recognized,
input is consumed but no feld in tm is set.
This format is a GNU extension following a GNU extension of strftime.
%G The year corresponding to the ISO week number.
Note: Currently, this is not fully implemented. The format is recognized,
input is consumed but no feld in tm is set.
This format is a GNU extension following a GNU extension of strftime.
%H
%k The hour as a decimal number, using a 24-hour clock (range 00 through
23).
%k is a GNU extension following a GNU extension of strftime.
%OH Same as %H but using the locale’s alternative numeric symbols.
%I
%l The hour as a decimal number, using a 12-hour clock (range 01 through
12).
%l is a GNU extension following a GNU extension of strftime.
%OI Same as %I but using the locale’s alternative numeric symbols.
%j The day of the year as a decimal number (range 1 through 366).
Leading zeroes are permitted but not required.
%m The month as a decimal number (range 1 through 12).
Leading zeroes are permitted but not required.
%Om Same as %m but using the locale’s alternative numeric symbols.
%M The minute as a decimal number (range 0 through 59).
Leading zeroes are permitted but not required.
%OM Same as %M but using the locale’s alternative numeric symbols.
%n
%t Matches any white space.
%p
%P The locale-dependent equivalent to ‘AM’ or ‘PM’.
This format is not useful unless %I or %l is also used. Another complica
tion is that the locale might not defne these values at all and therefore
the conversion fails.
%P is a GNU extension following a GNU extension to strftime.
%r The complete time using the AM/PM format of the current locale.
A complication is that the locale might not defne this format at all and
therefore the conversion fails.
%R The hour and minute in decimal numbers using the format %H:%M.
%R is a GNU extension following a GNU extension to strftime.
%s The number of seconds since the epoch, i.e., since 1970-01-01 00:00:00
UTC. Leap seconds are not counted unless leap second support is avail
able.
%s is a GNU extension following a GNU extension to strftime.


%S The seconds as a decimal number (range 0 through 60).
Leading zeroes are permitted but not required.
NB: The Unix specifcation says the upper bound on this value is 61, a
result of a decision to allow double leap seconds. You will not see the
value 61 because no minute has more than one leap second, but the myth
persists.
%OS Same as %S but using the locale’s alternative numeric symbols.
%T Equivalent to the use of %H:%M:%S in this place.
%u The day of the week as a decimal number (range 1 through 7), Monday
being 1.
Leading zeroes are permitted but not required.
Note: Currently, this is not fully implemented. The format is recognized,
input is consumed but no feld in tm is set.
%U The week number of the current year as a decimal number (range 0
through 53).
Leading zeroes are permitted but not required.
%OU Same as %U but using the locale’s alternative numeric symbols.
%V The ISO 8601:1988 week number as a decimal number (range 1 through
53).
Leading zeroes are permitted but not required.
Note: Currently, this is not fully implemented. The format is recognized,
input is consumed but no feld in tm is set.
%w The day of the week as a decimal number (range 0 through 6), Sunday
being 0.
Leading zeroes are permitted but not required.
Note: Currently, this is not fully implemented. The format is recognized,
input is consumed but no feld in tm is set.
%Ow Same as %w but using the locale’s alternative numeric symbols.
%W The week number of the current year as a decimal number (range 0
through 53).
Leading zeroes are permitted but not required.
Note: Currently, this is not fully implemented. The format is recognized,
input is consumed but no feld in tm is set.
%OW Same as %W but using the locale’s alternative numeric symbols.
%x The date using the locale’s date format.
%Ex Like %x but the locale’s alternative data representation is used.
%X The time using the locale’s time format.
%EX Like %X but the locale’s alternative time representation is used.


%y The year without a century as a decimal number (range 0 through 99).
Leading zeroes are permitted but not required.
Note that it is questionable to use this format without the %C format.
The strptime function does regard input values in the range 68 to 99 as
the years 1969 to 1999 and the values 0 to 68 as the years 2000 to 2068.
But maybe this heuristic fails for some input data.
Therefore it is best to avoid %y completely and use %Y instead.
%Ey The oﬀset from %EC in the locale’s alternative representation.
%Oy The oﬀset of the year (from %C) using the locale’s alternative numeric
symbols.
%Y The year as a decimal number, using the Gregorian calendar.
%EY The full alternative year representation.
%z The oﬀset from GMT in ISO 8601/RFC822 format.
%Z The timezone name.
Note: Currently, this is not fully implemented. The format is recognized,
input is consumed but no feld in tm is set.
%% A literal ‘%’ character.






*/
#include <stdio.h>
#include <time.h>
#include <string.h>

char * strptime (const char *s, const char *fmt, struct tm *tp);


const char *
parse_date (const char *input, struct tm *tm)
{
    const char *cp;
    
    /* First clear the result structure. */
    memset (tm, '\0', sizeof (*tm));
    
    /* Try the ISO format frst. */
    cp = strptime (input, "%F", tm);
    
    if (cp == NULL)
    {
        /* Does not match. Try the US form. */
        cp = strptime (input, "%D", tm);
    }
    return cp;
}


int main()
{
    time_t time = 1;
    struct tm *t = localtime(&time);
    
    struct tm *t2;
    t2 = localtime_r(&time, t2);
    
    printf("tm_sec = %d:%d\n", t->tm_sec, t2->tm_sec);
    printf("tm_min = %d:%d\n", t->tm_min, t2->tm_min);
    printf("tm_hour = %d:%d\n", t->tm_hour, t2->tm_hour);
    printf("tm_mday = %d:%d\n", t->tm_mday, t2->tm_mday);
    printf("tm_mon = %d:%d\n", t->tm_mon, t2->tm_mon);
    printf("tm_year = %d:%d\n", t->tm_year, t2->tm_year);
    printf("tm_wday = %d:%d\n", t->tm_wday, t2->tm_wday);
    printf("tm_yday = %d:%d\n", t->tm_yday, t2->tm_yday);
    printf("tm_isdst = %d:%d\n", t->tm_isdst, t2->tm_isdst);
    printf("tm_gmtoff = %d:%d\n", t->tm_gmtoff, t2->tm_gmtoff);
    printf("tm_zone = %s:%s\n", t->tm_zone, t2->tm_zone);
    
    
    
    char str[1024];
    // strftime(str, 1024, 
            // "%A %a %B %b %C %c \n"\
            // "%D %d %E %e %F %f \n"\
            // "%G %g %H %h %I %i \n"\
            // "%J %j %K %k \n"\
            // "%L %l %M %m %N %n \n"\
            // "%O %o %P %p %Q %q \n"\
            // "%R %r %S %s %T %t \n"\
            // "%U %u %V %v %W %w \n"\
            // "%X %x %Y %y %Z %z \n",
            // t2);
    strftime(str, 1024, 
            "%A %a %B %b %C %c %%\n",
            t2);
    printf("%s\n", str);
    
    struct tm t3;
    strptime(str, 
            "%A %a %B %b %C %c %%\n",
            &t3);
    
    
    printf("tm_sec = %d:%d\n", t->tm_sec, t3.tm_sec);
    printf("tm_min = %d:%d\n", t->tm_min, t3.tm_min);
    printf("tm_hour = %d:%d\n", t->tm_hour, t3.tm_hour);
    printf("tm_mday = %d:%d\n", t->tm_mday, t3.tm_mday);
    printf("tm_mon = %d:%d\n", t->tm_mon, t3.tm_mon);
    printf("tm_year = %d:%d\n", t->tm_year, t3.tm_year);
    printf("tm_wday = %d:%d\n", t->tm_wday, t3.tm_wday);
    printf("tm_yday = %d:%d\n", t->tm_yday, t3.tm_yday);
    printf("tm_isdst = %d:%d\n", t->tm_isdst, t3.tm_isdst);
    printf("tm_gmtoff = %d:%d\n", t->tm_gmtoff, t3.tm_gmtoff);
    printf("tm_zone = %s:%s\n", t->tm_zone, t3.tm_zone);
    
    
    return 0;
}