/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeDemo */

#ifndef _Included_NativeDemo
#define _Included_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeDemo
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeDemo_test
  (JNIEnv *, jobject);

/*
 * Class:     NativeDemo
 * Method:    test2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_NativeDemo_test2
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
