/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class int2int */

#ifndef _Included_int2int
#define _Included_int2int
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     int2int
 * Method:    function
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_int2int_function
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
