/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Main_square
  (JNIEnv *, jobject, jint);

/*
 * Class:     Main
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Main_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Main
 * Method:    volume
 * Signature: (FFF)F
 */
JNIEXPORT jfloat JNICALL Java_Main_volume
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
